{"guns" : [
    {
      "name": "P2020",
      "class": "pistol",
      "ammo": "Light Rounds",
      "magSize": "10",
      "reloadTime": "1.25",
      "dps": "102",
      "bodyDamage": "12",
      "headDamage": "18",
      "legDamage": "10.8",
      "sps": "8.5",
      "modes": "Single",
      "projectileSpeed": "18500",
      "drawTime": "0.25",
      "description": "The standard pistol and probably the weakest gun current in Apex Legends. It's passable when you don't have anything and can be quick to deal damage if - IF - you hit your shots",
      "imageUrl": "p2020.png"
    },
    {
      "name": "RE-45 Auto",
      "class": "pistol",
      "ammo": "Light Rounds",
      "magSize": "15",
      "reloadTime": "2.12",
      "dps": "143",
      "bodyDamage": "11",
      "headDamage": "16",
      "legDamage": "9.9",
      "sps": "13",
      "modes": "Auto",
      "projectileSpeed": "19500",
      "drawTime": "0.25",
      "description": "The RE-45 trades a little damage and a little bit of reload time on the P2020 but makes up for it by being fully automatic. A larger clip size is nice but be careful of the horizontal and vertical recoil",
      "imageUrl": "re45.png"
    },
    {
      "name": "Wingman",
      "class": "pistol",
      "ammo": "Heavy Rounds",
      "magSize": "6",
      "reloadTime": "2.10",
      "dps": "139.5",
      "bodyDamage": "45",
      "headDamage": "90",
      "legDamage": "40.5",
      "sps": "3.1",
      "modes": "Single",
      "projectileSpeed": "18000",
      "drawTime": "0.25",
      "description": "The Wingman is basically the Hand Cannon in Fortnite: powerful and slow. It's a high skill-ceiling weapon and best used by someone who trusts their own precision and sharpshooting",
      "imageUrl": "wingman.png"
    },
    {
      "name": "EVA-8 Auto",
      "class": "shotgun",
      "ammo": "Shotgun Shells",
      "magSize": "8",
      "reloadTime": "3.00",
      "dps": "126",
      "bodyDamage": "7",
      "headDamage": "10",
      "legDamage": "5.6",
      "sps": "2",
      "modes": "Auto",
      "projectileSpeed": "16000",
      "drawTime": "0.45",
      "description": "The most forgiving shotgun in Apex Legends with incredible fast rate of fire sets the EVA-8 apart from the rest. Its damage per shot can't compete with the Peacekeeper but the EVA's flexibility more than makes up for it",
      "imageUrl": "eva8.png"
    },
    {
      "name": "Peacekeeper",
      "class": "shotgun",
      "ammo": "Shotgun Shells",
      "magSize": "6",
      "reloadTime": "3.50",
      "dps": "106.7",
      "bodyDamage": "10",
      "headDamage": "15",
      "legDamage": "8",
      "sps": "0.97",
      "modes": "Single",
      "projectileSpeed": "16000",
      "drawTime": "0.45",
      "description": "The Peacekeeper fires 11 pellets in a star formation with each shot allowing it to deal phenomenal damage. It's the slowest shotgun so the question is whether your twitch-aiming is good enough to hit your shots. All in all the Peacekeeper is the best Shotgun around with the exception of the Mastiff - though the Peacekeeper has a longer effective range",
      "imageUrl": "peacekeeper.png"
    },
    {
      "name": "Mozambique",
      "class": "shotgun",
      "ammo": "Shotgun Shells",
      "magSize": "3",
      "reloadTime": "2.60",
      "dps": "99",
      "bodyDamage": "15",
      "headDamage": "22",
      "legDamage": "13.5",
      "sps": "2.2",
      "modes": "Auto",
      "projectileSpeed": "10000",
      "drawTime": "0.45",
      "description": "The Mozambique is the laughing stock of the Apex Legends weapons roster and has been acknowledged by the devs at Respawn as being underpowered. The compact triangle formation of its 3-shot burst gives it a slightly longer effective range than the others but still - pretty awful",
      "imageUrl": "mozambique.png"
    },
    {
      "name": "Mastiff",
      "class": "shotgun",
      "ammo": "Unique",
      "magSize": "4",
      "reloadTime": "1.70",
      "dps": "187.2",
      "bodyDamage": "18",
      "headDamage": "36",
      "legDamage": "18",
      "sps": "1.3",
      "modes": "Single",
      "projectileSpeed": "12000",
      "drawTime": "0.45",
      "description": "The Mastiff is a legendary weapon in Apex Legends with its own unique shotgun shells: 20 shots with this colossal weapon! It's by far the most powerful of all shotguns at close-range dealing a whopping 36 damage with each of the eight bullets it fire with every pull of the trigger",
      "imageUrl": "mastiff.png"
    },
    {
      "name": "G7 Scout",
      "class": "sniper",
      "ammo": "Light Rounds",
      "magSize": "10",
      "reloadTime": "3.00",
      "dps": "135",
      "bodyDamage": "30",
      "headDamage": "60",
      "legDamage": "21.75",
      "sps": "4.5",
      "modes": "Single",
      "projectileSpeed": "31500",
      "drawTime": "0.60",
      "description": "The Scout is an excellent and surprisingly versatile sniper rifle able to perform well at long and even close ranges. It deals less damage than its fellow snipers but has a much higher rate of fire and benefits from extended mag attachments. Damage from multiple shots equates to the same damage from a single shot from the Longbow or Kraber",
      "imageUrl": "g7.png"
    },
    {
      "name": "Longbow DMR",
      "class": "sniper",
      "ammo": "Heavy Rounds",
      "magSize": "5",
      "reloadTime": "3.66",
      "dps": "66",
      "bodyDamage": "55",
      "headDamage": "110",
      "legDamage": "39.88",
      "sps": "1.2",
      "modes": "Single",
      "projectileSpeed": "30500",
      "drawTime": "0.90",
      "description": "The Longbow is an excellent long-range choice with twice the damage per shot of the Scout. It has a fairly decent rate of fire (though nothing like as fast as the Scout). The special Hop-Up attachment gives the Longbow extra headshot damage making the Longbow truly a force to be reckoned with",
      "imageUrl": "longbow.png"
    },
    {
      "name": "Triple Take",
      "class": "sniper",
      "ammo": "Energy Ammo",
      "magSize": "5",
      "reloadTime": "3.40",
      "dps": "86.25",
      "bodyDamage": "23",
      "headDamage": "46",
      "legDamage": "16.68",
      "sps": "1.25",
      "modes": "Single (3-shot spread)",
      "projectileSpeed": "32000",
      "drawTime": "0.90",
      "description": "The Triple Take is nicknamed the firework for its very distinctive firing audio. This strange weapon could be described as a long-range shotgun; each pull of the trigger fires three shots in a packed triangle formation. This makes the gun great at mid-range battles but pretty terrible at long-distance - pretty bizarre for a sniper rifle",
      "imageUrl": "triple_take.png"
    },
    {
      "name": "Kraber .50 CAL",
      "class": "sniper",
      "ammo": "Unique",
      "magSize": "4",
      "reloadTime": "4.30",
      "dps": "150",
      "bodyDamage": "125",
      "headDamage": "250",
      "legDamage": "90.63",
      "sps": "1.2",
      "modes": "Single",
      "projectileSpeed": "29500",
      "drawTime": "1.20",
      "description": "The Kraber is one of two legendary weapons in Apex Legends and sports its own unique ammo - meaning you only get 8 shots. It's a phenomenally powerful bolt-action sniper capable of dealing 250 headshot damage in a single shot and sports a built-in 6x-10x scope for perfect snipes over immense distances",
      "imageUrl": "kraber.png"
    },
    {
      "name": "Devotion",
      "class": "lmg",
      "ammo": "Energy Ammo",
      "magSize": "44",
      "reloadTime": "3.63",
      "dps": "255",
      "bodyDamage": "17",
      "headDamage": "34",
      "legDamage": "12.75",
      "sps": "15",
      "modes": "Auto (Wind-Up)",
      "projectileSpeed": "33500",
      "drawTime": "0.70",
      "description": "The Devotion is currently top of many gun rankings in Apex Legends because of its awesome fire rate and DPS. The Turbocharger Hop-Up attachment really makes it shine but definitely reduces the gun's sizeable warm-up period after firing. Not really a gun to rely on against close-range attackers - you'll probably end up dead before you have the time to get your fire rate up",
      "imageUrl": "devotion.png"
    },
    {
      "name": "M600 Spitfire",
      "class": "lmg",
      "ammo": "Heavy Rounds",
      "magSize": "35",
      "reloadTime": "3.33",
      "dps": "180",
      "bodyDamage": "20",
      "headDamage": "40",
      "legDamage": "16",
      "sps": "9",
      "modes": "Auto",
      "projectileSpeed": "27500",
      "drawTime": "0.70",
      "description": "The Spitfire is surprisingly accurate for an LMG with decent DPS (nothing compared to Devotion though) and gets easier to manage at medium ranges. Often found in the hands of the top players in Apex Legends at the moment",
      "imageUrl": "spitfire.png"
    },
    {
      "name": "Havoc",
      "class": "ar",
      "ammo": "Energy Ammo",
      "magSize": "25",
      "reloadTime": "3.20",
      "dps": "201.6",
      "bodyDamage": "18",
      "headDamage": "36",
      "legDamage": "13.5",
      "sps": "11.2",
      "modes": "Auto",
      "projectileSpeed": "30500",
      "drawTime": "0.60",
      "description": "The first gun ever added to Apex Legends. The Havoc is a tricky gun and a lot of its performance is dependent on different attachments. You can choose the Turbocharger which eliminate wind-up-time before it starts firing in full-auto or the Selectfire Receiver. Overall a fast-firing AR that deals whopping damage once it gets going",
      "imageUrl": "havoc.png"
    },
    {
      "name": "VK-47 Flatline",
      "class": "ar",
      "ammo": "Heavy Rounds",
      "magSize": "20",
      "reloadTime": "3.10",
      "dps": "160",
      "bodyDamage": "16",
      "headDamage": "32",
      "legDamage": "12",
      "sps": "10",
      "modes": "Single/Auto",
      "projectileSpeed": "26000",
      "drawTime": "0.60",
      "description": "The Flatline is basically the baseline Assault Rifle in terms of stats. It has decent flat damage and a high clip size especially with attachments. Unfortunately it's nothing special and many consider it left in the dust by the R-301",
      "imageUrl": "vk47.png"
    },
    {
      "name": "Hemlok Burst",
      "class": "ar",
      "ammo": "Heavy Rounds",
      "magSize": "18",
      "reloadTime": "2.80",
      "dps": "108",
      "bodyDamage": "18",
      "headDamage": "36",
      "legDamage": "13.5",
      "sps": "15",
      "modes": "Single/Burst",
      "projectileSpeed": "27500",
      "drawTime": "0.60",
      "description": "A burst weapon that fires 3 bullets in extremely quick succession. If you're accurate you can deal over 100 damage in the space of about 0.2 seconds. Unfortunately the Hemlok's burst mode can't compete with the short-range DPS of many other weapons. Many players will give up the Hemlok for a good ol' Carbine",
      "imageUrl": "hemlok.png"
    },
    {
      "name": "R-301 Carbine",
      "class": "ar",
      "ammo": "Light Rounds",
      "magSize": "18",
      "reloadTime": "3.20",
      "dps": "189",
      "bodyDamage": "14",
      "headDamage": "28",
      "legDamage": "10.5",
      "sps": "13.5",
      "modes": "Single/Auto",
      "projectileSpeed": "29000",
      "drawTime": "0.60",
      "description": "The R-301 Carbine is the best AR on offer at the moment (or at least on par with the a Turbocharged Havoc). You trade a bit of damage for a faster rate of fire and an easier ride in general. Low recoil and a high bullet speed makes the Carbine excellent at most ranges (it can even be used to great effect at long range if you switch to single-shot mode). Almost no recoil",
      "imageUrl": "r301.png"
    },
    {
      "name": "Alternator",
      "class": "smg",
      "ammo": "Light Rounds",
      "magSize": "16",
      "reloadTime": "2.23",
      "dps": "130",
      "bodyDamage": "13",
      "headDamage": "19",
      "legDamage": "10.4",
      "sps": "10",
      "modes": "Auto",
      "projectileSpeed": "19500",
      "drawTime": "0.35",
      "description": "The Alternator is slow-firing but packs decent damage for an SMG. It has very high vertical but very minimal horizontal recoil. Put an extended mag or holo on it to take advantage of the gun's exceptionally quick reload time. Just don't expect to out-damage a good Assault Rifle or LMG",
      "imageUrl": "alternator.png"
    },
    {
      "name": "R-99",
      "class": "smg",
      "ammo": "Light Rounds",
      "magSize": "18",
      "reloadTime": "2.45",
      "dps": "216",
      "bodyDamage": "12",
      "headDamage": "18",
      "legDamage": "9.6",
      "sps": "18",
      "modes": "Auto",
      "projectileSpeed": "21000",
      "drawTime": "0.35",
      "description": "Because of its higher fire rate the R-99 will outperform the Alternator at close-range. It's currently the most sought-after baseline SMG in Apex Legends. At longer ranges the R-99's high recoil will often let you down unless you have a long of experience with this weapon",
      "imageUrl": "r99.png"
    },
    {
      "name": "Prowler Burst",
      "class": "smg",
      "ammo": "Heavy Rounds",
      "magSize": "20",
      "reloadTime": "2.60",
      "dps": "122.78",
      "bodyDamage": "14",
      "headDamage": "21",
      "legDamage": "11.2",
      "sps": "20",
      "modes": "Burst (5-shot)",
      "projectileSpeed": "18000",
      "drawTime": "0.35",
      "description": "This punchy burst SMG is... alright... until you manage to get your hands on an accompanying Selectfire Receiver Hop-Up attachment - then it becomes one of Apex Legends' most powerful weapons. Overall reliability falls short compared to an R-99",
      "imageUrl": " prowler.png"
    }
  ]
} 